### ISSUE TITLE
(M2) REST controllers and application logic services

### ISSUE THREAD

**Issue by darbach** [north-star-sharing/north-star-sharing.github.io#11]
- [x] REST controller classes with controller methods supporting the relevant operations.
- [x] Controller classes must be defined in a controller subpackage.
- [x] Service classes must be defined in a service subpackage.
- [x] Code must be linked on Github Pages.
- [x] Basic persistence logic may be included in the REST controller methods.
- [x] More advanced application logic must be implemented in service classes annotated with @Service and injected into the relevant controller classes.
- [x] Access control and state transition rules must be enforced on the server side.
- [x] Common error conditions must not be allowed to result in an HTTP 500 response
- [x] POST operations that add a resource to a collection must return an HTTP **201 Created** response status code, as well as a valid Location header.
- [ ] Operations that delete items from a server-side database--or expect not to return body content--must be implemented using HTTP DELETE requests, and must return a **204 No content** response.
- [x] All non-scalar (i.e. object or array) response and request bodies must use the JSON (application/json) format.
- [x] Any request or response body that contains only a scalar value (i.e. a single value, whether numeric, string, or Boolean) may use JSON or plain-text (text/plain).
- [x] Resource collections must be accessed by the consumer via plural-named URL paths (e.g. /passphrases).
- [x] Individual resources in such a collection should be accessed by providing a resource identifier within the collection URL (e.g. /passphrases/201).

**Comment by rbrazell1** [comment]
we don't have a delete interface.
