### ISSUE TITLE
(M3) Functional Documentation: Basic User Instructions, 3 points

### ISSUE THREAD

**Issue by darbach** [north-star-sharing/north-star-sharing.github.io#17]
- [x] Your documentation must include basic instructions for using and administering (as applicable) the system after it’s running.

https://ddc-java.github.io/capstone-project/milestone-3.html#basic-user-instructions-3-points

**Comment by rbrazell1** [comment]
I have started the instructions in  a markdown file.

**Comment by rbrazell1** [comment]
This is captured in the instructions
