### ISSUE TITLE
(M3) Technical Documentation: Build instructions, 4 points

### ISSUE THREAD

**Issue by darbach** [north-star-sharing/north-star-sharing.github.io#23]
- [x] Your documentation must include instructions for building and running all front-end and back-end components (as applicable). These instructions should be as complete as possible, starting with locating & cloning the source repositories, and incorporating any sensitive content, then continuing all the way through the build, preload (if applicable), and run steps.

https://ddc-java.github.io/capstone-project/milestone-3.html#build-instructions-4-points

**Comment by rbrazell1** [comment]
I have started basic build instructions, and user instructions.

**Comment by rbrazell1** [comment]
This is captured in the read me
