### ISSUE TITLE
(M3) Copyright & license, 4 points

### ISSUE THREAD

**Issue by darbach** [north-star-sharing/north-star-sharing.github.io#24]
Minimally, this must include:
- [x] Copyright/license info for your team’s work, including the relevant LICENSE file in all code repositories, notices in your README.md in all repositories (code and documentation) and in a license notice Markdown or HTML file in your documentation repository.
- [x] Copyright/license info for all 3rd-party components, listed (along with your own project copyright & license info) in the notice.md license documentation page. Important: Review the licenses of all components to be as confident as possible that the notices you are including satisfy the license requirements of the copyright owners.

https://ddc-java.github.io/capstone-project/milestone-3.html#copyright--license-information-4-points

**Comment by rbrazell1** [comment]
We will need to add any additional notices if we bring in more things
