### ISSUE TITLE
(M3) Implementation: Intuitive GUI, 9 points

### ISSUE THREAD

**Issue by darbach** [north-star-sharing/north-star-sharing.github.io#25]
- [ ] The client application should include multiple pages or screens, with rational, intuitive navigation between them. For Android apps, the “Understanding navigation” section of the Material Design guidelines should be used as a starting point for planning and implementing navigation features in the app.

https://ddc-java.github.io/capstone-project/milestone-3.html#intuitive-gui-9-points

**Comment by rbrazell1** [comment]
This would be better if the galleries loaded correctly.
