### ISSUE TITLE
(M3) Implementation: Effective use of databases (relational or non-relational) for maintaining persistent data, 10 points

### ISSUE THREAD

**Issue by darbach** [north-star-sharing/north-star-sharing.github.io#27]
- [x] The primary data store should be maintained on the server side, whether in a database controlled completely by the back-end application, or a cloud database service (e.g. Firebase). The front-end application may maintain its own disconnected or semi-connected database; however, accidental or deliberate deletion of the front-end database (or the entire front-end application) should not significantly impact the system as a whole.

- [x] Regardless of platform, any required pre-population of database contents should be implemented for execution as a deployment step, or on system startup, without direct action required by the end-user.

**Comment by rbrazell1** [comment]
This has been captured in the build instructions.
