### ISSUE TITLE
(M3) Implementation: Custom icons and other graphics, 6 points

### ISSUE THREAD

**Issue by darbach** [north-star-sharing/north-star-sharing.github.io#30]
- [x] Such elements may include—but are certainly not limited to—launcher icons/logos, button graphics, menu icons, welcome/splash-screen graphics, etc.

https://ddc-java.github.io/capstone-project/milestone-3.html#custom-icons-and-other-graphics-6-points

**Comment by rbrazell1** [comment]
I've added a hand full of basic custom icons, including the launcher icon.

**Comment by rbrazell1** [comment]
I feel that we have done these well enough for the mile stone, going forward it will be good to keep working on the style of the app.
